version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:80' # Mapeia a porta 8080 do host para a porta 80 do contêiner
        volumes:
            - .:/var/www/html # Monta o diretório do projeto no contêiner
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
